# Authors: Sylvain MARIE <sylvain.marie@se.com>
#          + All contributors to <https://github.com/smarie/python-pydocquery>
#
# License: 3-clause BSD, <https://github.com/smarie/python-pydocquery/blob/master/LICENSE>
"""Project root init.

isort:skip_file
"""
from pydocquery.queries import (
    RootError,
    Metadata,
    NestedPrimitive,
    SimplePrimitive,
    Query,
    QueryError,
    InvalidQueryUsageError,
    MissingQueryTargetError,
    query_base,
    is_same_query,
    hash_query,
    MISSING,
    NEGATED_MISSING,
    Asc,
    Desc,
    SortingQuery,
)
from pydocquery.queries_compilation import compile_query, evaluate_query


try:
    # -- Distribution mode --
    # import from _version.py generated by setuptools_scm during release
    from ._version import version as __version__
except ImportError:
    # -- Source mode --
    # use setuptools_scm to get the current version from src using git
    from os import path as _path

    from setuptools_scm import get_version as _gv

    __version__ = _gv(_path.join(_path.dirname(__file__), _path.pardir, _path.pardir))


__all__ = [
    "__version__",
    # submodules
    "queries",
    "queries_compilation",
    "queries_lib",
    # symbols
    "RootError",
    "Metadata",
    "NestedPrimitive",
    "SimplePrimitive",
    "Query",
    "QueryError",
    "InvalidQueryUsageError",
    "MissingQueryTargetError",
    "query_base",
    "is_same_query",
    "hash_query",
    "MISSING",
    "NEGATED_MISSING",
    "Asc",
    "Desc",
    "SortingQuery",
]
